tari-project/gh-pilot

github-api/src/lib.rs, github-api/src/models_plus/mod.rs, github-api/src/models_plus/pull_request.rs, server/src/actions/essentials.rs, server/src/actions/github_action.rs, server/src/server.rs
This PR adds an addional Github action that will add or remove the
`P-conflict` label if the PR is in a merge-conflict state.
A rule to check this status on every update to PRs has also been added.
=> feat: add merge conflict label action

cli/src/issue.rs, github-api/src/api/issue.rs, github-api/src/github_provider.rs, github-api/src/provider_traits/issue_provider.rs, server/src/actions/github_action.rs
If you try remove a non-existent label, github returns a 404, which isn't great for hygiene. So
- accept a `only_if_exists` flag to remove_label
- add a fetch_labels call in support
- update merge_conflict action to check for existence first
=> feat: add if_exists check to remove_label

cli/src/issue.rs, github-api/src/github_provider.rs, github-api/src/provider_traits/issue_provider.rs, server/src/actions/github_action.rs
Report more details, by returning whether we hit the APi to remove the label or not.
Prettier log messages.
=> feat: tidy up logs on merge conflict action

cli/src/issue.rs, cli/src/main.rs, cli/src/pull_request.rs, cli/src/user.rs, github-api/src/github_provider.rs, server/src/actions/closure_action.rs, server/src/actions/github_action.rs, server/src/heuristics/pull_requests.rs, server/src/predicates/pull_request.rs, server/src/pub_sub/actor.rs, server/src/routes.rs, server/src/server.rs
Put emoji prefixes in log messages to make it easier to pick them out in the log noise (eps on TRACE level).
=> refactor(logs): add emojis to logs to make 'em prettier

cli/Cargo.toml, cli/src/cli_def.rs, cli/src/issue.rs, cli/src/labels.rs, cli/src/main.rs, cli/src/pretty_print.rs, cli/src/pull_request.rs, github-api/src/api/client_proxy.rs, github-api/src/api/error.rs, github-api/src/api/mod.rs, github-api/src/api/repo_request.rs, github-api/src/github_provider.rs, github-api/src/provider_traits/mod.rs, github-api/src/provider_traits/repo_provider.rs, github-api/src/wrappers/mod.rs, github-api/src/wrappers/new_label.rs, presets/labels.yml
Given a file like
```yml
- name: C-bug
description: Something isn't working
color: d73a4a
- name: CR-insufficient_context
description: 'The PR body does not provide enough information to fully describe the changes requested.'
color: FBE057
- name: 'C-Documentation'
description: 'This PR or issue is related to documentation.'
color: 56a6ff
- name: 'C-Duplicate'
description: This issue or pull request already exists
color: cfd3d7
- name: good first issue
description: Good for newcomers
color: 7057ff
- name: P-conflicts
description: The PR has merge conflicts that need to be resolved
color: D50030
```
Simply run 
```
ghp-cli -o {owner} -r {repo} labels assign -f path/to/file.yml
```
and all your labels are added to your repo. 🚀 
If you have a repo with labels you like already...
```
ghp-cli …
```
=> feat: add labels from yml files to repo

cli/src/cli_def.rs, cli/src/contributors.rs, cli/src/labels.rs, cli/src/main.rs, cli/src/pretty_print.rs, github-api/src/api/repo_request.rs, github-api/src/github_provider.rs, github-api/src/models/user.rs, github-api/src/provider_traits/mod.rs, github-api/src/provider_traits/repo_provider.rs, github-api/src/webhooks/mod.rs, server/src/main.rs, server/src/pub_sub/actor.rs, server/src/routes.rs, server/src/utilities.rs
Adds a feature to pull the list of contributors to a repo, filtering out
bots and orgs.
the CLI command
chp_cli -o {owner} -r {repo} contributors
will print a list of contributors to the terminal
Adds a trait and githubProvider impl to fetch a repo's list of
contributors.
The /contributors endpoint only returns the first 100 contributors, so
beyond this, you need to use another method of tracking project
contributors.
The repo request method filters out non USER accounts and empty logins
before returning the contributor list
=> feat: add query to pull repo contributors

cli/src/cli_def.rs, cli/src/pull_request.rs, github-api/src/api/pull_request.rs, github-api/src/github_provider.rs, github-api/src/graphql/data/pr_review_counts.graphql, github-api/src/graphql/mod.rs, github-api/src/graphql/review_counts.rs, github-api/src/provider_traits/mod.rs, github-api/src/provider_traits/pull_request_provider.rs
You can now get a summary of PR reviews with the reviews subcommand.
```
$ ghp-cli -o "tari-project" -r "tari" pull-request -n 4234 reviews
┌──────────────────────────────────────────────────────┐
│ PR Reviews          feat: add sender to instructions │
│ Reviewers           sdbondi brianp SWvheerden        │
│ Approvals           3                                │
│ Changes requested   false                            │
└──────────────────────────────────────────────────────┘
```
=> feat: graphql query for review counts

cli/src/cli_def.rs, cli/src/contributors.rs, cli/src/issue.rs, cli/src/pretty_print.rs, cli/src/pull_request.rs, github-api/src/api/pull_request.rs, github-api/src/github_provider.rs, github-api/src/graphql/data/check_run_status.graphql, github-api/src/graphql/data/sample_check_run.json, github-api/src/graphql/mod.rs, github-api/src/graphql/run_status.rs, github-api/src/models/common.rs, github-api/src/models/date_time.rs, github-api/src/provider_traits/mod.rs, github-api/src/provider_traits/pull_request_provider.rs
Adds the `check` sub-command to the pull-request PR command that fetches
the last set of check runs from the last commit on the PR.
Example:
```
ghp-cli -o "tari-project" -r "tari" pull-request -n 4270 check
[2022-10-07T11:38:56Z INFO  ghp_cli] 🚀 Ignition! Launching Github Pilot in Authenticated Mode.
Check Run status for commit https://github.com/tari-project/tari/commit/32987d6d8c4cf768f8962285d625281aea602c74 at 2022-07-14T07:12:30Z
Overall result: "SUCCESS"
┌───────────────────────────────────────────────────────────────────────────────┐
│ Name                Completed At           Result      Status        Required │
│ clippy              2022-07-14T07:20:24Z   "SUCCESS"   "COMPLETED"   true     │
│ check stable        2022-07-14T07:19:53Z   "SUCCESS"   "COMPLETED"   false    │
│ …
```
=> feat: add cli command to fetch last check run

cli/src/contributors.rs, cli/src/pull_request.rs, github-api/src/github_provider.rs, github-api/src/graphql/pr_comments.rs, github-api/src/graphql/review_counts.rs, github-api/src/models/date_time.rs, github-api/src/models/user.rs, github-api/src/provider_traits/repo_provider.rs, github-api/src/webhooks/pr_event.rs, github-api/src/wrappers/issue_id.rs, server/Cargo.toml, server/src/actions/essentials.rs, server/src/actions/github_action.rs, server/src/actions/merge_action/action_params.rs, server/src/actions/merge_action/executor.rs, server/src/actions/merge_action/message.rs, server/src/actions/merge_action/mod.rs, server/src/actions/mod.rs, server/src/pub_sub/actor.rs, server/src/server.rs
`merge_action` is a Github Pilot action that can automatically merge PRs based on given criteria.
This is a very basic version of this action, and will not be as full-featured as some other products like merge-queue, or bors; but, using other actions, and labels as a messaging system, you _can_ build up some fairly complex behaviour.
I'll also add additional features to this action in future, after allowing for a decent period to get feedback on how this action is performing.
This action is the most complex written to date, so it has its own module, rather than putting everything in one file.
The merge action behaviour is controlled with these parameters:
*  acks_required: how many ACK-type messages are required,
*  ack_patterns: A list of regex patterns to identify as ACK messages,
* …
=> feat: add auto-merge action

github-api/src/wrappers/issue_id.rs, server/src/actions/merge_action/executor.rs
The review check function now gives better feedback in the logs as to its decision.
Example:
```
[...] ⏫ PR tari-project/gh-pilot#27 has 1 comments
[...] ⏫ PR tari-project/gh-pilot#27 has 1 / 1 required ACKs
[...] 👀 PR tari-project/gh-pilot#27 has 0 reviews, 0/0 required, changes_requested: false
[...] ⏫ Checking status of last Check Run for PR tari-project/gh-pilot#27
[...] ⏫ The roll up status is Some(PENDING)
[...] ⏫ PR has 6 checks, 3 passed / 5 required.
```
=> feat: improve logs in merge action status feedback

github-api/src/github_event.rs, github-api/src/models/pull_request.rs, github-api/src/models/status_check_events.rs, github-api/src/models_plus/check_suite_event.rs, github-api/src/models_plus/mod.rs, github-api/src/models_plus/pull_request_review_comment_event.rs, github-api/src/models_plus/pull_request_review_event.rs, server/src/actions/merge_action/executor.rs
Merge Action won't always be triggered on a PR event. But if we can, we should still try and merge the PR if the conditions match. This means extracting the related PR for the event.
This PR adds a `related_pr` method to GithubEvent which tries to dig out the PR info from the different event types.
=> fix: extract related pr in merge action

.github/workflows/test.yml
Drop the stable rust, and only test in release mode.
=> test: speed up gha

server/src/actions/closure_action.rs, server/src/actions/essentials.rs, server/src/actions/github_action.rs, server/src/actions/merge_action/executor.rs, server/src/actions/merge_action/message.rs, server/src/pub_sub/action_result.rs, server/src/pub_sub/actor.rs, server/src/pub_sub/messages.rs, server/src/pub_sub/mod.rs, server/src/server.rs
Actions can now return an ActionResult, which is currently one of
*    Success,
* ConditionsNotMet,
* Failed,
* Indeterminate,
The idea being that rules can then respond accordingly with different actions based on whether the base action passed, failed, etc.
Making this a reality meant switching the PubSubActor messages to return FutureResonse types, and switching up the internals on PubSubActor a bit to make everything async-aware.
=> feat: actions return a result

cli/src/cli_def.rs, cli/src/issue.rs, cli/src/main.rs, cli/src/pull_request.rs
Provide the `--id` argument for issue and pull-request queries, allowing you to easily override the owner/repo arg in the form `{owner}/{repo}#{number}`
A little quality of life improvement
=> feat: add shorthand pr/issue id cli argument

github-api/src/graphql/review_counts.rs, server/src/utilities.rs
use `map_or_else`
don't use `Default::default`
=> fix: deepsource lint suggestions

server/src/pub_sub/actor.rs, server/src/rules.rs, server/src/server.rs
Adds support for a set of actions to be run if and only if, all the "execute" actions return successfully.
These actions are submitted when building rules:
```
RuleBuilder::new("(AutoLabel) Pull request complexity")
.when(PullRequest::more_complex_than(PullRequestComplexity::High))
.execute(Actions::github().add_label("CR-one_job").build())
.then(Actions::email().sender())
.submit(),
```
=> feat: add "then" actions

cli/src/pull_request.rs, github-api/src/graphql/check_run_status.rs, github-api/src/graphql/data/check_run_status.graphql, github-api/src/graphql/data/sample_check_run.json, github-api/src/graphql/mod.rs, github-api/src/graphql/run_status.rs, github-api/src/models/date_time.rs, server/src/actions/merge_action/executor.rs
* The status roll up result sometimes returns a false negative External tests (e.g. CircleCI) were not included in the results * Repeated tests were being double-counted.
* Update graphQL query to return external tests too
* Only use status rollup if it returns success
* Refactor RunStatus to hold a HashMap of only the latest result of each test
* Coerce GHA and external tests into the same RunStatus struct Provide helper functions in RunStatus to clean up the MergeAction code Tidy up nested `impl From` mess a bit
* Manage to avoid using `collect` when zipping two monstrously nested iterators :)
=> fix: handle status checks better

rules.yaml, server/Cargo.toml, server/src/config.rs, server/src/rule_set.rs, server/src/server.rs
- Rules are now loaded from rules.yaml
- the base set of rules have been reformatted as YAML (except the ones with closures, which cannot be yaml'd)
=> feat: load rules from external file

server/src/config.rs, server/src/main.rs
The host and port were hardcoded until now.
This adds the feature to read in the host, port and ruleset path from environment variables, or else use defaults if they're missing.
=> feat: set host and port from env vars

.github/workflows/clippy-check.yml, .github/workflows/test.yml
Add the GA type to the end of the cache. Simce partial matches are used in `restore-keys` this should make more efficient use of GA caches, which are now named to be more specific the longer the match
=> fix: improve cache naming

server/README.md, server/src/cli.rs, server/src/lib.rs, server/src/main.rs
If any CLI argument is provided (including -h), then the README.md file will be displayed as a form of user guide / help text, as well as the currently configured envar variables, which may aid in troubleshooting.
**Note**: The README is compiled into the application. You do not have to bundle it with any distribution.
```text
gh-pilot$ ghp-server -h
Make your Github CI processes fly.
Github pilot server enables granular and complex workflows for Github projects that goes beyond what is 
possible in Github Actions.
The server process is straightforward and extensible:
1. Github's webhook service makes a POST call to the server `github/webhook` endpoint.
2. The data from the Github event is compared against the set of Github Pilot rules (defined in `rules.yml`).
3. For any rule that …
```
=> feat: add cli help text

sample.env
You still need to actually set the variable, but sample.env is updated with the new recommended default setting
=> chore: set actix web default logging to warn
